name: Book Library Room

on:
  schedule:
    - cron: '17 * * * *'   # ✅ Every hour at minute 0
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 🕒 Print GitHub Trigger Time and and Current Time in Calgary
        run: |
          echo "GitHub UTC Time:"
          date -u
          echo "MDT Time (Calgary):"
          TZ="America/Edmonton" date

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: 🤖 Run bot
        env:
          RUN_DATES: "2026-04-07,2026-04-08"
          BOOKING_DATES: "2026-05-07,2026-05-08"

          LOCATION_ID: ${{ secrets.LOCATION_ID }}
          GROUP_SIZE: ${{ secrets.GROUP_SIZE }}
          MEETING_TITLE: ${{ secrets.MEETING_TITLE }}
          USERNAME: ${{ secrets.USERNAME }}
          PIN: ${{ secrets.PIN }}

        run: python bot.py
